### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [limaoscarjuliet/cafe#1]
much of what you are doing with pg-promise, it supports on a higher level, so you are re-writing what's already there.

* you do not need to use `connect` when executing just one query. And when executing multiple ones, method `task` is the recommended approach.
* method `tx` provides automatic support for transactions, which is what you should be using.

These changes can simplify your code a lot, and make it more reliable ;)

**Comment by fatmonkey99** [comment]
Yes, learning proper node while writing this code ;-) Thx for the hint, will clean up this week, do proper validation, etc.

**Comment by limaoscarjuliet** [comment]
Thx again, cleaned up simple cases, working on transactions next.

**Comment by vitaly-t** [comment]
you are re-inventing the wheel when trying to organize a transaction manually, while pg-promise supports transactions automatically. See [Transactions](https://github.com/vitaly-t/pg-promise#transactions).
